// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX9FOryJ8BRYKf6dENUPVB1p-AgdWB5DM',
    appId: '1:205980912739:web:e1d6f9819f409f655cfc56',
    messagingSenderId: '205980912739',
    projectId: 'basicapp-7ed4b',
    authDomain: 'basicapp-7ed4b.firebaseapp.com',
    storageBucket: 'basicapp-7ed4b.firebasestorage.app',
    measurementId: 'G-4B640LSCWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFf5bVn5b02cEHkIcl-zTuqxXWiqS0zeU',
    appId: '1:205980912739:android:10fb306c1a55b1975cfc56',
    messagingSenderId: '205980912739',
    projectId: 'basicapp-7ed4b',
    storageBucket: 'basicapp-7ed4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3e2q6FikZ-wYDyKRPqCY4iFPOYtN7N0',
    appId: '1:205980912739:ios:7a4e4b299ef503815cfc56',
    messagingSenderId: '205980912739',
    projectId: 'basicapp-7ed4b',
    storageBucket: 'basicapp-7ed4b.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3e2q6FikZ-wYDyKRPqCY4iFPOYtN7N0',
    appId: '1:205980912739:ios:7a4e4b299ef503815cfc56',
    messagingSenderId: '205980912739',
    projectId: 'basicapp-7ed4b',
    storageBucket: 'basicapp-7ed4b.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX9FOryJ8BRYKf6dENUPVB1p-AgdWB5DM',
    appId: '1:205980912739:web:df81a74a032e68b35cfc56',
    messagingSenderId: '205980912739',
    projectId: 'basicapp-7ed4b',
    authDomain: 'basicapp-7ed4b.firebaseapp.com',
    storageBucket: 'basicapp-7ed4b.firebasestorage.app',
    measurementId: 'G-LNQNB7LFSB',
  );
}
